### ISSUE TITLE
[BUG][CV] Missing data validation in vision checks

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#1058]
**Describe the bug**
Most checks validate the task type, but they do not validate that the data has the properties necessary for running the check, such as a valid batch_to_images method, or batch_to_labels. 

**Expected behavior**
Look at the example validation in the `initialize_run `method of image_property_drift.py
We want to add such validations to all checks.

**Comment by matanper** [comment]
> we should think if it's possible to make those function run only if it didn't failed during validation

What do you mean failed during validation? If the validation raise non-deepchecks error then all the run is stopped. If it's deepchecks error like not implemented or incorrect format, our method is to run the checks that are able to run, and not run the ones that aren't. Therefore in order to stop the checks that can't run you need to assert you have the needed data
