### ISSUE TITLE
[FEAT][CHAR] new design for suite output (notebook)

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1501]
Refactor the suite output to the following format: 

1. Put everything into a single accordion cell (gives frame + expand and close capability) 
- select default open / close.
3. Add 4 (filter) toggles / checkboxes on top “pass”,”fail”,”other”, “didn’t run”. By default all should be selected.
4. No more tabs - they are replaced by the toggles (action item b)

Open questions (review alternatives and approve with team):
Summary table structure (*it should dynamically show the relevant checks dependent on toggle status + easy navigation link like we have today):
- Full “condition table”? (showing also checks without conditions…)
- Only check name + symbol (pass/fail/none…)

Problems with a lot of scrolling.
- Another accordion? Per check? Per sub-group?
- None?

**Comment by noamzbr** [comment]
I think the answer to the condition table issue was one of the following:

1. suite result will only contain TOC (not fully decided if with or without pass fail status). Full condition summary will be displayable using new check result member `.condition_summary()`
2. condition summary table will be in it's own accordion above the accordion of all the check plots

**Comment by noamzbr** [comment]
## Clarification of Scope
This task is about finalizing the characterizing of the new suite output from a technical standpoint. How will it look like? What it will use? How would it work with not widgets?

The actual implementation in the package with tests and all will be done in #1508

**Comment by yromanyshyn** [comment]
@ItayGabbay @shir22 @noamzbr @Nadav-Barak 

> Add 4 (filter) toggles / checkboxes on top “pass”,”fail”,”other”, “didn’t run”. By default all should be selected.

== point 1 ==

and how it is different from the tabs?

== point 2 ==

I think that in order to implement described behavior via toggles/checkboxes 
we would need to use what ipywidgets documentation calls [kernel linking](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Events.html#The-difference-between-linking-in-the-kernel-and-linking-in-the-client), 
and I am not sure how this functionality works in different envs (colab, kaggle, 
jupyterlab, etc) plus it will not work with documentation

tabs on other hand do not require this and no any additional js libraries

so, I think it could potentially complicate our code and add more edge cases
but from my point of view, there would not be any benefits from this 

> Problems with a lot of scrolling.

maybe let's just add a check-level accordion?

that is how it could look (recorded video)
https://user-images.githubusercontent.com/71635444/170273390-9ae4a495-3449-470a-9fa9-8c5b5bb13759.mp4

**Comment by ItayGabbay** [comment]
@yromanyshyn about point 1 - the main problem today is that the output is really large even with tabs, and the user is losing focus on they notebook. So we want to start in a collapsed state, and then when the user clicks to expand it will open and show the output.

About point 2 - I agree it sounds a bit problematic... wonder what should we do about it.
In general, we want it to be interactive, maybe it'd be easier to just render our own HTML and js? @matanper 

In addition, I suggest you see how pandas-profiling has solved these issues @yromanyshyn

**Comment by yromanyshyn** [comment]
@ItayGabbay @matanper 
> In addition, I suggest you see how pandas-profiling has solved these issues @yromanyshyn

`pandas-profiling` uses two strategies:

-- first one --

serialize (render) report to the ipywidgets

in this case, all the problems which we discussed via slack are also present 

-- second one (default) --

serialize the report to the independent HTML page and display it via iframe.

in this case, the suggestion made by Matan to implement totally our own design 
has a sense the only not serious issue that I encountered for now is that the iframe must 
have static size (width, height), and also it will have its own scrollbar
