### ISSUE TITLE
[BUG] improve class performance condition details

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1535]
**Is your feature request related to a problem? Please describe.**
the details are too long

**Describe the solution you'd like**
maybe a list per metric instead of every class in a different line.

![Screen Shot 2022-05-30 at 11 50 46](https://user-images.githubusercontent.com/26321553/170957748-4313e3ad-8d45-46d4-b94e-92ba47fb579e.png)

**Comment by matanper** [comment]
Another possible bug in the condition:
```
diff = {score_name: _ratio_of_change_calc(score, test_scores_dict[score_name])
           for score_name, score in train_scores_dict.items()}
```
the train & test would not necessarily will have the same classes, so need to decide what to do when there is a class missing

**Comment by Nadav-Barak** [comment]
There are two different issues here:
1. Confirm and fix the bug matan mentioned
2. Rereview how the details which we provide for this check are calculated, maybe use n_top_show to only include in details info regarding the n_top_show most interesting class (same logic as for the display plots) or review other possibilities.

For issue number 2, first try and see whether this issue is also relevant for other checks as well (Performance Report is a likely candidate).
Then come up with a suggestion for what to display in the "More Info" box and confirm it with the team. Next, implement it.

**Comment by matanper** [comment]
@Nadav-Barak About point 2 what I did in a few checks: take the number of failing classes/scores and the one which failed the most (lowest score) and then write message like:
"Found X failing classes. Lowest score is y for class z"
