### ISSUE TITLE
[FEAT][Docs] metrics guide

### ISSUE THREAD

**Issue by Nadav-Barak** [deepchecks/deepchecks#1604]
Create a user guide / doc describing all the performance metrics we support and link all performance related checks to this doc (similar to drift guide).

Discuss how to divide the metrics into sections, how to connect explanations of tabular and vision.

**Comment by Nadav-Barak** [comment]
Basically create something similar in fashion to the amazing [Drift Guide](https://docs.deepchecks.com/dev/user-guide/index.html). Need to discuss:
1.  how to divide the different metrics into sub sections
2. how to handle metrics that are common to both vision and tabular (classification)
3. should we mention explicitly which are implemented ourself and which are imported (e.x from sklearn)
4. Should we fully explain the metric internally or also add a link
5. Techinically - how to write equations in a rst file 

In addition in metric guide add a section demonstrating how to use those metric in the tabular performance report and in the vision Class Performance

**Comment by Nadav-Barak** [comment]
Hey @TheSolY saw that you are taking this on so I will add what was discussed with Bressler.

- The section should be divided by task type (and not data type) i.e binary classification, multiclass classification, regression, object detection etc
- can see here the metrics there we currently have (ones in red do not exist yet) [link](https://docs.google.com/document/d/10cfF8HyQ_tau6D1k7Ip-i3aBedx_VP_B1VRDtCW3ddE/edit)
- In general we should be able to run on mentioned metric if the user gives as the metric name as a string (the string names of sklearn). Need to verify this is the case and if not open an issue
- section on custom metric, we discussed it is needed but did not went into details
- Check out Arize metrics guide for inspiration

**Comment by TheSolY** [comment]
Issue updates:
We have decided to separate the guide to 2 parts: blog post with theoretical background- intro to metrics, user guide with practical instructions - using metrics with Deepchecks.

User Guide 
DoD:
The user guide RST file is ready and added to our docs including all of the ways to use metrics that we support.

Tasks:

- [ ] Move the theoretical background to a separate document - 0.5 SP
- [ ] Add a short paragraph about the motivation to use metrics at the beginning of the document. - 0.5 SP
- [ ] Change the structure of the guide, examples should be inline instead of at the end of the document - 0.5 SP
- [ ] Add instructions and code examples to usage in suites (currently there are only checks) - 1 SP
- [ ] *after implementation* add instructions and example to pass strings instead of scorers and a list of supported strings 
- [ ] *after implementation* add instruction and example for using sklearn metrics in vision - 0.5 SP
- [ ] *After implementation* Update the default scorer for a single metric - 0.5 SP
- [ ] Add instructions on the averaging options - 0.5 SP
- [ ] Add a link to the blogpost to the motivation

Blog Post:
DoD:
The blogpost is published.

Tasks:

- [ ] Add information about how we calculate the metrics we implemented - 1 SP
- [ ] Add information about the averaging options in multiclass cases - 0.5 SP
- [ ] Add a link to the metrics userguide

**Comment by Nadav-Barak** [comment]
Additional task: After metric guide is complete update doc string and examples of relevant checks to direct users to the metric guide.

**Comment by TheSolY** [comment]
@Nadav-Barak please open a separate issue for this
