### ISSUE TITLE
[BUG] some links in the data classes implementation tutorial lead to 404

### ISSUE THREAD

**Issue by TheSolY** [deepchecks/deepchecks#1675]
https://docs.deepchecks.com/stable/user-guide/vision/data-classes/index.html#what-do-you-need-to-implement
The faulty links are marked in yellow 
![image](https://user-images.githubusercontent.com/99395146/174994087-4136fc43-cb95-4e84-9c1c-16259e51450f.png)

**Comment by DanBasson** [comment]
hi
i'm new to open source.
can i take this issue?
i believe that '/stable' should be added to the html path

**Comment by matanper** [comment]
Hey @DanBasson, thank you for your willingness to contribute 😃 

We are generating the docs using a tool called `sphinx`, so the links are not manually written, they are generated using a specific directive which in this case is not updated/correct. 

To help you start do the following:
1. Fork deepchecks repository
2. Look under `docs/source` for the data classes guide mentioned above
3. Look for examples in other files how we reference internal docs pages (`:docs:`)
4. Fix the issue, then run `make docs` in order to build the docs locally and test the fix (WARNING: this action takes a long time, about 1 hour)
5. Open pull request for us to approve 

If you have any questions feel free to comment here or [reach me at our slack community](https://deepcheckscommunity.slack.com/team/U02KL4CFXB9)

**Comment by ItayGabbay** [comment]
Hen @DanBasson are you still planning to take this?

**Comment by DanBasson** [comment]
I'm struggling to create a dev environment at the moment.
if it's urgent, i can let it go.
if not, i assume it'll take me another week or so.

thanks

**Comment by ItayGabbay** [comment]
OK then! let me know if you need any help with creating the dev env

**Comment by TheSolY** [comment]
Here as well the VisionData User Guide link leads to 404 https://docs.deepchecks.com/en/stable/user-guide/vision/data-classes/ClassificationData.html
![image](https://user-images.githubusercontent.com/99395146/177507208-d196710a-abb4-4efa-aa5a-af3259bc0109.png)

**Comment by kishore-s-15** [comment]
> Hey @DanBasson, thank you for your willingness to contribute smiley
> 
> We are generating the docs using a tool called `sphinx`, so the links are not manually written, they are generated using a specific directive which in this case is not updated/correct.
> 
> To help you start do the following:
> 
> 1. Fork deepchecks repository
> 2. Look under `docs/source` for the data classes guide mentioned above
> 3. Look for examples in other files how we reference internal docs pages (`:docs:`)
> 4. Fix the issue, then run `make docs` in order to build the docs locally and test the fix (WARNING: this action takes a long time, about 1 hour)
> 5. Open pull request for us to approve
> 
> If you have any questions feel free to comment here or [reach me at our slack community](https://deepcheckscommunity.slack.com/team/U02KL4CFXB9)

Hi,
    I am starting off with open source journey with `Deepchecks`. Can I work on this issue ? I have looked into what you have mentioned and made the necessary changes in my local version. Can I open a pull request for this issue ?

**Comment by DanBasson** [comment]
Sure

**Comment by kishore-s-15** [comment]
@ItayGabbay Could you assign me for this issue ?

**Comment by kishore-s-15** [comment]
> Sure

Thanks @DanBasson

**Comment by TheSolY** [comment]
@kishore-s-15 assigned :)

**Comment by kishore-s-15** [comment]
`.user_id` file has been created when I have used `make docs`. Should I commit that file ?
