### ISSUE TITLE
[BUG] need to reconsider how we get check param

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1739]
**Describe the bug**
we get the check param by the variables defined by the check and not by what has been passed to it
also some params are functions or classes (such as metric) which can cause problems in serialization
 
**Expected behavior**
get the params the check was initialized with

**Screenshots**
![Screen Shot 2022-07-07 at 10 26 42](https://user-images.githubusercontent.com/26321553/177719261-baae28c2-fc5e-4ad7-8d27-f5ede6717040.png)

**Comment by yromanyshyn** [comment]
suggest implementing a decorator that would collect and store initial parameters under the name `__initial_params__`

```python
def initial_params_collector(fn):
   assert fn.__name__ == '__init__'
   def decorator(self, *args, **kwargs):
         init_signature = signature(fn)
         ...
         self.__initial_params__ = <collected params dict>
         return fn(*args, **kwargs)
   return fn

class SomeCheck:
    @initial_params_collector
    def __init__(self, ...):
       ...
```

**Comment by yromanyshyn** [comment]
**Task description:**

in order to support serialization/deserialization of the check instances, we need a mechanism that will be able to capture check init parameters (parameters that were passed to the constructor) and will be able to serialize them to JSON. The current implementation relies on the idea that each check init parameter is stored within an instance under the same name and unchanged which is obviously wrong.

For more info take a look at:
- `deepchecks.core.checks.BaseCheck.config()`  method
- `deepchecks.core.checks.BaseCheck.params()`  method


**TODO:**
- suggest a mechanism to capture check instance init parameters
- explore and suggest a solution for serialization of complex check init parameters (like lambdas, instances of other classes)
