### ISSUE TITLE
[FEAT] have an option to pass classes to predit_proba scorers + name positive label in binary classification

### ISSUE THREAD

**Issue by JKL98ISR** [deepchecks/deepchecks#1982]
see issue #1981 for some background

we need to be able to pass the classes (label+prediction) to the scorers to also be able to prevent some errors if the label+predict does contain all the classes in scorers that use predict_proba (in those scorers there will not be a bug but an error from sklearn)

we need to be able to utilise the option to pass the classes (as will be from the linked issue) to the scorers.

**Comment by TheSolY** [comment]
This bug happens when not all of the possible classes appear in the dataset, so the size of the model output doesn't match the number of unique label values. 
Sklearn has a feature to accept an array of labels, as the scorers' parameter 'labels', we can adopt. 

tasks:

- [ ] Decide on the API to pass the classes. for example, pass a list to check init. 1SP
- [ ] Refactor the relevant checks and scorers to support it. 2SP
- [ ] Add a usage example to the documentation. 0.5 SP

**Comment by JKL98ISR** [comment]
I think it is better to pass it in the run.
  1. we pass the dataset in the run and labels are connected to dataset
  2. a user will be able to pass the labels to the suite using the kwargs
  3. only need to add it to the context init, a bit faster and easier to access

**Comment by Nadav-Barak** [comment]
Agreed, will be passed in run

**Comment by Nadav-Barak** [comment]
Will be solved via https://github.com/deepchecks/deepchecks/issues/2108
