### ISSUE TITLE
[BUG] custom model wrapper documentation: classes_ property is missing

### ISSUE THREAD

**Issue by mglowacki100** [deepchecks/deepchecks#2364]
In the documenation: 
https://docs.deepchecks.com/stable/user-guide/tabular/supported_models.html#adapting-your-custom-model
there is a template:
```
class MyModelWrapper:
    def predict(self, data: pd.DataFrame) -> np.ndarray:
        # Implement based on base model's API.
        ...
    def predict_proba(self, data: pd.DataFrame) -> np.ndarray:
        # Implement based on base model's API, only required for classification tasks.
        ...
    @property
    def feature_importances_(self) -> pd.Series:  # optional
        # Return a pandas Series with feature names as index and their corresponding importance as values.
        ...
```
It is not complete, as also `classes_` property need to be provided to avoid warnings about missing feature names. Here is example of autogluon model wrapper:
```
class AutoGluonWrapper:
    def predict(self, data: pd.DataFrame) -> np.ndarray:
      return predictor.predict(data).to_numpy()
        
    def predict_proba(self, data: pd.DataFrame) -> np.ndarray:
      return predictor.predict_proba(data).to_numpy()

    @property
    def classes_(self):
      return predictor.class_labels
    
    @property
    def feature_importances_(self) -> pd.Series:
      return predictor.feature_importance(test_data, silent=True)  
```

**Comment by noamzbr** [comment]
Thanks for reporting @mglowacki100. What library is responsible for the warning btw?
Would you be interested in opening a PR for this issue?

**Comment by mglowacki100** [comment]
Hi @noamzbr,
1. Libary responsible for warnings: https://auto.gluon.ai/stable/index.html 
2. I've put here example of autogluon wrappers:
https://colab.research.google.com/gist/mglowacki100/ee63b2b6746a634a29c250d79b63cd72/deepchecks_autogluon_wrappers.ipynb
- all versions have `classes_`
- version 2 - model is passed explicite as parameter, it looks more elegant for me 
3. Besides `classes_` autogluon has slightly different api for feature importance (https://auto.gluon.ai/stable/api/autogluon.predictor.html#autogluon.tabular.TabularPredictor.feature_importance), either:
- there is a need for parameter 'features_stage='transformed'` like in version 3 or 
- dataset need to be provided (version 1 and 2)
4. I'm interested in PR. I think it could be done in two parts: 
a) addidng information about `classes_` and general information that api need to match exactly (feature importance from autogluon is good example) to the documentation
b) link to detailed notebook with full example (my autogluon example could be a starter) 
6. Are there guidelines for contributors similar to this: https://xgboost.readthedocs.io/en/stable/contrib/index.html ?

**Comment by noamzbr** [comment]
Hi @mglowacki100, sounds good! Correct me if I'm wrong, but seems like these two issues (needing `class_` and `feature_importance()`) are unique to autogluon models?

Before we start developing an example of how to wrap a autogluon model, could it be the case the autogluon models can be used "as is" without wrapping them at all? Trying it out in your notebook, it seems that the current problem with running it as is it that it outputs pd.Series and pd.DataFrame from the predict and predict_proba functions, rather than numpy arrays. I'm currently getting a bug from our internal `sequence_to_numpy` method.

Considering that, I think that the first step in supporting autogluon should be trying supporting it as-is, which entails makeing deepchecks support series / dataframe predictions and probas. Would you be interested in contributing on this?

The contribution guide can be found here - https://github.com/deepchecks/deepchecks/blob/main/CONTRIBUTING.rst. To commonicate more instantly you're welcome to join to also join our slack community https://join.slack.com/t/deepcheckscommunity/shared_invite/zt-1p763uclu-nnxBq2p5hVKMt2~BYf3Z_A

**Comment by mglowacki100** [comment]
@noamzbr I'm interested in PR.
Indeed predictions could be automatically converted from pd.DataFrame to numpy array, so autogluon will be supported, but with warnings regarding class names and feature importance.
Warnings could be resolved, analogously to this: https://github.com/deepchecks/deepchecks/blob/main/deepchecks/tabular/integrations/h2o.py
or maybe autogluon could change/extend their API.
Btw. I've checked couple of other popular libs:
- LightGBM should be supported out of the box: https://lightgbm.readthedocs.io/en/v3.3.2/pythonapi/lightgbm.LGBMClassifier.html#lightgbm.LGBMClassifier
- similarly CatBoost:
https://catboost.ai/en/docs/concepts/python-reference_catboostclassifier
- Xgboost I don't see `classes_` in documentation https://xgboost.readthedocs.io/en/stable/python/python_api.html#module-xgboost.sklearn

**Comment by noamzbr** [comment]
So my suggestion - start with a PR that will add out of the box support (with warnings), then if you got the time you can add an example to resolve the warnings.

**Comment by mglowacki100** [comment]
I think this change should fix issue:
```
def sequence_to_numpy(sequence: t.Sequence):
    """Convert a sequence into a numpy array."""
    if isinstance(sequence, np.ndarray):
        return sequence.flatten()
    elif isinstance(sequence, t.List):
        return np.asarray(sequence).flatten()
    elif isinstance(sequence, pd.Series): #NEW
        return sequence.to_numpy().flatten() #NEW
    else:
        raise DeepchecksValueError('Trying to convert a non sequence into a flat list.')
```
but let me double-check.
