### ISSUE TITLE
Suite output text - fix first part

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#431]
1. Add explanation for the “!” (warning) 2. add link to docs where written (or remove wording), where it says:"Suites, checks and conditions can all be modified (see tutorial [link])."

**Comment by yromanyshyn** [comment]
@noamzbr 

**point 1**
sorry I did not get you, where exactly do we need to add an explanation?

**point 2**
we do not have an example that shows how to modify existing suites or checks. Maybe it would be better to replace it with

```
If needed you can add your own check to the suite (link to the `add_a_custom_check` example) or replace an existing one
```

but, honestly, I think this sentence is redundant/ in my opinion, it will be weird for the user-defined suites to contain links to the deepchecks resources

**Comment by shir22** [comment]
Hey, about 1 -
it's
"Each check may contain conditions (which results in ✓ / ✖ / ! )"
so to write something like
"Each check may contain conditions (which will result in pass / fail / warning, represented by ✓ / ✖ / !)"

and about the tutorial link, it should be to here:
https://docs.deepchecks.com/en/stable/examples/guides/create_a_custom_suite.html
(yes the current link is broken cause it's under "latest" but soon will be in "stable" as well)

About the redundant part - I agree, I think it the future we'll want to drop the "suite" oral explanation completely, once we have a wide enough user base, but for initial adoption of "lazy users that never heard about us and want to make the minimal effort to understand what it's about" then it can be useful, and that's why this whole explanation exists in the first place.

**Comment by yromanyshyn** [comment]
@shir22 I got you, please take a look at the PR #499

**Comment by shir22** [comment]
Great, thanks.
Requested a small fix, then will approve (feel free to ping me on slack if I don't see it)
