### ISSUE TITLE
Improve check example notebooks

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#543]
Example notebooks standard should match the feature drift notebook

**Comment by shir22** [comment]
Notes:
Presenting what the check does, how it works
Preparing all data in an ordered way
Preferably using a dataset from the datasets in the package (and transforming it, rather than creating a dataset from "0")
Making sure the output is user facing (imagine that print-screens will be used to demonstrate this check), nice column names, etc.
Include demonstration of condition(s)


First checks to improve:
1. Trust Score Comparison (Distribution)
2. Simple Model Comparison (Performance)
3. Performance Report (Performance) - The combined one (including overfit)
4. Single Feature Contribution (Methodology) - of the revamped one
5. Unused Features (Methodology)
6. Train Test Samples Mix (Methodology)
7. Dominant Frequency Change Check (Integrity)
8. Mixed Types (Integrity)
9. String Mismatch & String Mismatch Comparison (Integrity)
10. Segment Performance (Performance)
11. Calibration Metric Check (Performance)

**Comment by noamzbr** [comment]
I'll do Trust Score Comparison
