### ISSUE TITLE
[DOCS] Solve sphinx errors when building docs

### ISSUE THREAD

**Issue by ItayGabbay** [deepchecks/deepchecks#571]

**Comment by shir22** [comment]
After completion make docs build fail if there are errors...
Otherwise - there are failed links that we won't be aware of

Current examples:
link to API reference at the bottom of
[Dataset Object](https://docs.deepchecks.com/en/latest/user-guide/dataset_object.html)
([see link in raw](https://docs.deepchecks.com/en/latest/_sources/user-guide/dataset_object.rst.txt))

and also link to api reference in [Key Concepts](https://docs.deepchecks.com/en/latest/user-guide/key_concepts.html)
[(see link in raw)](https://docs.deepchecks.com/en/latest/_sources/user-guide/key_concepts.rst.txt)
