### ISSUE TITLE
[FEAT][CV] Similar Image leakage check

### ISSUE THREAD

**Issue by noamzbr** [deepchecks/deepchecks#850]
Build a check testing if the same image appears in both train and test datasets.

**Comment by nirhutnik** [comment]
### DoD - 
Check + tests + notebook + condition in main

### Description
This check identifies if images exist both in train and test

### Inputs
seed - for the hash? Not really important.
No other inputs required.

### Outputs
check value - percentage of images that are the same. 
Also, return identifiers for these images - if filenames are not available, keep a local count of images.
display - ideally, which image repeats itself. However, as we do not have identifiers, this might be problematic.

### Logic - 
As we don't have an identifier for the images, and comparing pixel-by-pixel is not realistic, we should save a hash for each image and then count how many hashes repeat themselves.
If filenames are not available, keep a local count of images as identifiers.

### Tasks:
* Check whether there is a common way of getting image filenames or other identifiers via batch.
* If there is such a way, implement a possible logic that uses that instead of hash + returns those identifiers
* In any way, implement logic as described

**Comment by noamzbr** [comment]
Following a proposal by @omrysendik, this check will be implemented using a distance metric easy and fast to compute, such as the one in https://github.com/elisemercury/Duplicate-Image-Finder

**Comment by nirhutnik** [comment]
### Regarding this specific package:
Package is specifically not relevant, as it compares images between 2 folders (or within 1 folder).
The basic algorithm is just comparing the distance between pixels of image (after resizing to the same image size, recommended 50*50).

### So what can we use?
The basic method is to transform the image to some sort of space in which similar images are transformed to similar values.
The issue is what we define as "similar". The simplest option is what is done in the mention package - resize (and compress) the images to a 50*50 (or any other constant reasonable size), and compare the images in that space.
This captures images that are practically identical, such as 2 images shot almost at the same time.

Other complex methods can include more complex feature extraction (SIFT for example) or a pre-trained CNN feature space, an autoencoder encoding layer (same thing mostly). But these might catch similarity that is not interesting to us - if we have 2 images of the same building, taken at different angles, in different days - are these still too similar?

### Suggestion:
We can start by using the simplest algorithm - compress the images and compare them. We can save computing time by first only comparing basic properties (color histogram for example) and then check for further similarity in close images only. The issue is that we need to define relevant threshold for this similarity which will require research.

In any way, in comparing the images, we also need to define a threshold of "what is similar". We can use the one from the mentioned package but its supported by no research.

In general, I could not find any packages or code that does this similarity in a generalized, free to use way. So we will need to write at least part of it ourselves.

####Thorough review of different methods:
https://medium.com/@gabriel_83172/how-to-find-similar-images-using-math-a-gentile-introduction-to-image-retrieval-and-neural-67f3c987b643

####Good explanations on why duplication removing is important:
https://pyimagesearch.com/2020/04/20/detect-and-remove-duplicate-images-from-a-dataset-for-deep-learning/

**Comment by nirhutnik** [comment]
So, I think we need to discuss:
1. What do we mean by similar
2. How do we approach this and can we accept a "good enough" solution that at the beginning will be very sensitive (check that identifies identical images, and slightly distorted ones, but that's it).

I'm for the pixel-by-pixel difference for now, as it's quick and still useful. Can be done in 3 SPs in my opinion, including relevant threshold that is very sensitive. Not including performance improvements by using color histograms as this will add development time.

**Comment by omrysendik** [comment]
IMHO, it's totally OK to go with the "good enough" solution which is very sensitive.
I would just like to note that often you will find that data augmentation is done offline (and not in train time). (Yes, this is bad practice, but people do it).
In such a case, this check will fail and it's good that it does. So I guess you should just stress this to the users.
My point was to emphasize that control of the sensitivity may mitigate this.
Moving forward, there are methods in which can explicitly define the types of differences they are agnostic to.
I believe the repo I shared with you will detect two flipped images (a supposedly major and perhaps deliberate difference) as a duplicate.

To make a long story short: my humble recommendation is to proceed just as @nirhutnik mentioned but just be aware of the pitfalls.

**Comment by nirhutnik** [comment]
Thanks @omrysendik !
The package does support rotated images, was wondering myself whether this should be considered or not.
Also, one thing I haven't mentioned is that the images should be (IMO) scaled (by std, not minmax), so differences in original brightness would not count as different images.

**Comment by noamzbr** [comment]
Found the following blogpost:
https://medium.com/@somilshah112/how-to-find-duplicate-or-similar-images-quickly-with-python-2d636af9452f
That leads to the following package:
https://github.com/JohannesBuchner/imagehash

I believe this is the easiest way for an initial implementation. Should test it out on some lightly augmented images and see what threshold is needed for it to work well enough.
